name: Build and Publish Image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v4
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/dmgeowebsite:latest
    - name: Push image to docker hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push ${{ secrets.DOCKER_USERNAME }}/dmgeowebsite:latest
    - name: Copy docker-compose.yml to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AWSEC2_HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.AWSEC2_SSH_KEY }}
        source: "docker-compose.yml"
        target: "~/dm-geo-website" # Place it in the home directory

  deploy:

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
        with:
          host: ${{ secrets.AWSEC2_HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWSEC2_SSH_KEY }}
          envs: DOCKER_USER, LETSENCRYPT_EMAIL
          script: |
            cd ~/dm-geo-website
            docker-compose pull
            docker-compose up -d
            docker image prune -f
    
